version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      mstest-packages:
        patterns:
          - "MSTest.*"
    commit-message:
      include: "release-notes"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      include: "release-notes"
