<?xml version="1.0" encoding="utf-8"?>

<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- ServiceFabric.Mocks.csproj -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.ServiceFabric.Actors" Version="8.7.157" />
  </ItemGroup>

  <!-- ServiceFabric.Mocks.NetCoreTests.csproj -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.4.0" />
  </ItemGroup>

</Project>
